name: Build multi-arch docker images and publish on DockerHub

# Control when actions will run
# Triggers the workflow on push or pull request events but only for the main/master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level     
        required: false
        default: warning
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      #- '.github/workflows/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      #- '.github/workflows/**'
      - 'docs/**'
    schedule:
    - cron: '0 5 * * *' # everyday at 5am

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "release"
    release:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        
        # Set environment variables
        env:
        DOCKERHUB_SLUG: chourmovs/mopidy-gs-spotify





          # GitHub Action to build and push Docker images with Buildx.
# Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Github action to get branch or tag information without the /ref/* prefix
          - name: Get branch names
            id: branch-name
            uses: tj-actions/branch-names@v6

          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout
            uses: actions/checkout@v3

          # GitHub Action to extract metadata (tags, labels) for Docker.
          - name: Docker meta
            id: docker_meta
            uses: docker/metadata-action@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              images: |
                ${{ env.DOCKERHUB_SLUG }}
              tags: |
                type=schedule,pattern=latest
                type=semver,pattern={{version}}
                type=edge,branch=${{ steps.branch-name.outputs.default_branch }}
                type=raw,value=develop,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
                type=ref,event=branch,enable=${{ !(steps.branch-name.outputs.default_branch) && (github.ref != format('refs/heads/{0}', 'develop')) }}

          # GitHub Action to install QEMU static binaries.
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2

          # GitHub Action to set up Docker Buildx.
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            with:
              buildkitd-flags: "--debug"

          #   # GitHub Action to free disk space on Ubuntu action runners.
          # - name: Free Disk Space (Ubuntu)
          #   uses: jlumbroso/free-disk-space@main

          # Hack to fix Error "Value too large for defined data type;" on arm/v7 and linux/386  
          # https://github.com/crazy-max/ghaction-docker-buildx/issues/172
          # 1. Create Swapfile of 22GB (1MBx22K) size to increase hosts (virtual) ram
          # 2. Mount tempfs with max. size of Swapfile + host's Phys.RAM (max ~6 GB) to dockers filesystem /var/lib/docker (volumes, etc.)
          # Note: If tempfs is too small for build the runner will receive a shutdown signal
          - name: Hack docker filesystem to create small tmpfs for docker cache
            run: |
              df -h
              sudo swapon --show
              sudo dd if=/dev/zero of=/swapfile1 bs=1M count=22K 
              sudo chmod 600 /swapfile1
              sudo mkswap /swapfile1
              sudo swapon /swapfile1
              sudo swapon --show
              sudo free -h
              sudo systemctl stop docker
              sudo mount -t tmpfs -o size=25G tmpfs /var/lib/docker
              df -h
              sudo systemctl start docker
      
          # GitHub Action to login to DockerHub.
          -   name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  
          # GitHub Action to build and push Docker images with Buildx.
          - name: Build
            uses: docker/build-push-action@v3
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/amd64, linux/arm/v7, linux/arm64
              push: ${{ github.event_name != 'pull_request' }}
              tags: ${{ steps.docker_meta.outputs.tags }}
              no-cache: true
              build-args: |
                VERSION=${{ steps.docker_meta.outputs.version }}
                BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                VCS_REF=${GITHUB_SHA::8}
              labels: |
                ${{ steps.docker_meta.outputs.labels }}
                org.opencontainers.image.title=${{ env.DOCKERHUB_SLUG }}
                org.opencontainers.image.description=Docker image update notifier
                org.opencontainers.image.vendor=${{secrets.DOCKERHUB_USERNAME}}

          - name: Check manifest
            if: github.event_name != 'pull_request'
            run: |
              docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.docker_meta.outputs.version }}

          - name: Inspect image
            if: github.event_name != 'pull_request'
            run: |
              docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.docker_meta.outputs.version }}
              docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.docker_meta.outputs.version }}

          - name: Clear
            if: always() && github.event_name != 'pull_request'
            run: |
                rm -f 
           ${HOME}/.docker/config.json
